name: MicroBin
description: 'A tiny, self-contained, configurable paste bin and URL shortener written in Rust.'
tags:
- pastebin
source: https://github.com/szabodanika/microbin
website: https://microbin.eu/
icon: https://microbin.eu/img/logo-square.png
screenshots:
- https://microbin.eu/img/screenshot7.png
- https://microbin.eu/img/screenshot6.png
- https://microbin.eu/img/screenshot1.png
- https://microbin.eu/img/screenshot4.png
- https://microbin.eu/img/screenshot5.png
- https://microbin.eu/img/screenshot3.png
- https://microbin.eu/img/screenshot2.png