name: Illa
description: 'ILLA is a robust open source low-code platform for developers to build internal tools.'
tags:
- low-code
source: https://github.com/illacloud/illa-builder
website: https://illacloud.com
icon: https://avatars.githubusercontent.com/u/93245159?s=200&v=4
screenshots:
- https://www.illacloud.com/_next/image?url=https%3A%2F%2Fcdn.illacloud.com%2Fofficial-website%2Fimg%2Fhome%2FplayVideoCover.png&w=3840&q=75