apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: applications.kubero.dev
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: kubero.dev
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                pipline:
                  type: string
                phase:
                  type: string
                gitrepo:
                  type: string
                branch:
                  type: string
                autodeploy:
                  type: boolean
                domain:
                  type: string
                podsize:
                  type: string
                webreplicas:
                  type: integer
                workerreplicas:
                  type: integer
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: applications
    # singular name to be used as an alias on the CLI and for display
    singular: application
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Application
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - app