name: Serge Chat AI
status: beta
description: 'A web interface for chatting with Alpaca through llama.cpp. Fully dockerized, with an easy to use API.'
tags:
- LLM
- AI
source: https://github.com/serge-chat/serge
website: https://serge.chat
icon: https://avatars.githubusercontent.com/u/135821135?s=200&v=4
screenshots:
- https://github.com/TwiN/gatus/raw/master/.github/assets/dashboard-dark.png
devnotes:
- type: info
  message: Requires large Nodes with a lot of memory. >= 8GB recommended.