name: Symfony
description: 'Symfony is a PHP framework for web and console applications and a set of reusable PHP components.'
gitops: true
tags:
- framework
- php
source: https://github.com/symfony/symfony
website: https://symfony.com
icon: https://avatars.githubusercontent.com/u/143937?s=200&v=4
screenshots: